# Generated by Django 4.2.5 on 2023-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='phone'),
        ),
    ]
