# Generated by Django 4.2.5 on 2023-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
